markdown: redcarpet
permalink: /:categories/:title.html
url: 
lsi: false
pygments: true
safe: true
auto: false 

paginate: 8
paginate_path: "page:num"

# presonal config
domain: www.djhull.com
title: djhull's Blog
description: GitHub,FreeBSD,Centos,Python,PHP,MySQL,Redis,MongoDB ......
author: djshell
email: djshell#sina.com
github: djshell

config:
  js_dir:
  img_dir:
  css_dir:
